// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udlpneqwpshdwnodgwfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkbHBuZXF3cHNoZHdub2Rnd2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzgwMDAsImV4cCI6MjA2ODE1NDAwMH0.ROjVUyfNsvjW9g6lpM9h3fK8iod8Qne0K8pbsW5xuYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});